import 'dart:async';

import 'package:campusconnect/utilities/refresh_dedupe.dart';
import 'package:flutter_test/flutter_test.dart';

/// v9.2.2 (§2) — `RefreshDedupe` regression tests.
///
/// Covers the acceptance criteria of the v9.2.2 brief §2:
///  * concurrent refresh requests share ONE in-flight future;
///  * repeated initialization for an unchanged fingerprint does not re-run;
///  * a changed intelligence fingerprint DOES re-run;
///  * a forced (explicit) refresh always re-runs;
///  * logout/reset (`invalidate`) clears the gate so a new session refreshes.
void main() {
  group('RefreshDedupe.shouldRun', () {
    test('runs when nothing has been recorded yet', () {
      final gate = RefreshDedupe();
      expect(gate.shouldRun('uid-a', 'fp-1'), isTrue);
    });

    test('skips a repeat call with the SAME fingerprint (stale recs not '
        'regenerated by a rebuild)', () {
      final gate = RefreshDedupe();
      gate.record('uid-a', 'fp-1');
      expect(gate.shouldRun('uid-a', 'fp-1'), isFalse);
    });

    test('runs again when the fingerprint CHANGED (legitimate state change)',
        () {
      final gate = RefreshDedupe();
      gate.record('uid-a', 'fp-1');
      expect(gate.shouldRun('uid-a', 'fp-2'), isTrue);
    });

    test('is per-user — a different uid never inherits another user record',
        () {
      final gate = RefreshDedupe();
      gate.record('uid-a', 'fp-1');
      expect(gate.shouldRun('uid-b', 'fp-1'), isTrue);
    });

    test('force ALWAYS runs, even for an identical fingerprint', () {
      final gate = RefreshDedupe();
      gate.record('uid-a', 'fp-1');
      expect(gate.shouldRun('uid-a', 'fp-1', force: true), isTrue);
    });

    test('re-runs once maxAge has elapsed (long-lived session freshness)', () {
      var now = DateTime(2026, 1, 1, 12);
      final gate = RefreshDedupe(
        maxAge: const Duration(hours: 6),
        clock: () => now,
      );
      gate.record('uid-a', 'fp-1');
      expect(gate.shouldRun('uid-a', 'fp-1'), isFalse);

      now = now.add(const Duration(hours: 5, minutes: 59));
      expect(gate.shouldRun('uid-a', 'fp-1'), isFalse);

      now = now.add(const Duration(minutes: 2));
      expect(gate.shouldRun('uid-a', 'fp-1'), isTrue);
    });

    test('maxAge of zero pins the fingerprint for the whole session', () {
      var now = DateTime(2026, 1, 1);
      final gate = RefreshDedupe(
        maxAge: Duration.zero,
        clock: () => now,
      );
      gate.record('uid-a', 'fp-1');
      now = now.add(const Duration(days: 30));
      expect(gate.shouldRun('uid-a', 'fp-1'), isFalse);
    });
  });

  group('RefreshDedupe in-flight sharing', () {
    test('exposes the active future for the same key only', () async {
      final gate = RefreshDedupe();
      final completer = Completer<void>();
      gate.begin('uid-a', completer.future);

      expect(gate.isActive, isTrue);
      expect(gate.inFlightFor('uid-a'), same(completer.future));
      expect(gate.inFlightFor('uid-b'), isNull);

      completer.complete();
      await completer.future;
      await Future<void>.delayed(Duration.zero);
      expect(gate.isActive, isFalse);
    });

    test('two concurrent callers share the SAME future (one backend call)',
        () async {
      final gate = RefreshDedupe();
      var backendCalls = 0;

      Future<void> callRefresh() async {
        final inFlight = gate.inFlightFor('uid-a');
        if (inFlight != null) return inFlight;

        backendCalls++;
        final future = Future<void>.delayed(
          const Duration(milliseconds: 5),
        );
        gate.begin('uid-a', future);
        await future;
        gate.record('uid-a', 'fp-1');
      }

      await Future.wait([callRefresh(), callRefresh(), callRefresh()]);

      // All three callers collapsed into exactly one backend invocation.
      expect(backendCalls, 1);
    });

    test('the active handle auto-clears only for its OWN future (a late '
        'completion cannot clobber a newer refresh)', () async {
      final gate = RefreshDedupe();
      final first = Completer<void>();
      gate.begin('uid-a', first.future);

      // A second refresh supersedes the first (e.g. after a fingerprint
      // change) before the first future settles.
      final second = Completer<void>();
      gate.begin('uid-a', second.future);

      // The stale first future completes late — it must NOT clear the handle
      // now owned by the second refresh.
      first.complete();
      await Future<void>.delayed(Duration.zero);
      expect(gate.isActive, isTrue);
      expect(gate.inFlightFor('uid-a'), same(second.future));

      second.complete();
      await Future<void>.delayed(Duration.zero);
      expect(gate.isActive, isFalse);
    });

    test('a failing tracked future does not throw out of begin()', () async {
      final gate = RefreshDedupe();
      final failing = Future<void>.error(StateError('boom'));
      expect(() => gate.begin('uid-a', failing), returnsNormally);
      // Observe the original error so the test framework does not report it.
      await failing.catchError((Object _) {});
      await Future<void>.delayed(Duration.zero);
      expect(gate.isActive, isFalse);
    });

    test('a FAILED refresh is not recorded — a retry is always allowed',
        () async {
      final gate = RefreshDedupe();
      // Simulate the service: begin + error → no `record`.
      final failing = Future<void>.error(StateError('backend down'));
      gate.begin('uid-a', failing);
      await failing.catchError((Object _) {});
      await Future<void>.delayed(Duration.zero);

      expect(gate.shouldRun('uid-a', 'fp-1'), isTrue);
    });
  });

  group('RefreshDedupe reset lifecycle', () {
    test('invalidate drops every record so a re-login refreshes again', () {
      final gate = RefreshDedupe();
      gate.record('uid-a', 'fp-1');
      gate.record('uid-b', 'fp-2');
      expect(gate.shouldRun('uid-a', 'fp-1'), isFalse);

      gate.invalidate();

      expect(gate.shouldRun('uid-a', 'fp-1'), isTrue);
      expect(gate.shouldRun('uid-b', 'fp-2'), isTrue);
    });

    test('invalidate bumps the epoch and clears the in-flight handle', () {
      final gate = RefreshDedupe();
      final before = gate.epoch;
      final completer = Completer<void>();
      gate.begin('uid-a', completer.future);
      expect(gate.isActive, isTrue);

      final after = gate.invalidate();

      expect(after, before + 1);
      expect(gate.epoch, after);
      expect(gate.isActive, isFalse);
      expect(gate.inFlightFor('uid-a'), isNull);

      completer.complete();
    });

    test('the logout/login lifecycle collapses a re-login burst to one call',
        () async {
      final gate = RefreshDedupe();
      var backendCalls = 0;

      Future<void> refresh() async {
        final inFlight = gate.inFlightFor('uid-a');
        if (inFlight != null) return inFlight;
        if (!gate.shouldRun('uid-a', 'fp-1')) return;
        backendCalls++;
        final future = Future<void>.delayed(const Duration(milliseconds: 2));
        gate.begin('uid-a', future);
        await future;
        gate.record('uid-a', 'fp-1');
      }

      // Session 1.
      await refresh();
      await refresh(); // implicit duplicate — skipped
      expect(backendCalls, 1);

      // Logout clears the gate.
      gate.invalidate();

      // Session 2 (re-login): must refresh once more.
      await refresh();
      expect(backendCalls, 2);
    });

    test('clear(key) drops a single user without touching the others', () {
      final gate = RefreshDedupe();
      gate.record('uid-a', 'fp-1');
      gate.record('uid-b', 'fp-2');

      gate.clear('uid-a');

      expect(gate.shouldRun('uid-a', 'fp-1'), isTrue);
      expect(gate.shouldRun('uid-b', 'fp-2'), isFalse);
    });
  });
}
