const loginRoute = '/login/';
const registerRoute = '/register/';
const notesRoute = '/notes/';
const verifyEmailRoute = '/verify-email/';
const profileRoute = '/profile/';
const editProfileRoute = '/edit-profile';
const profileSetupRoute = '/profile-setup';
const notificationsRoute = '/notifications';
const settingsRoute = '/settings'; // v6.6
const resumeReviewRoute = '/resume-review'; // v6.7
