// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY6pPYWVQAL4tONCV-W-i9l_5Jh3yRdjA',
    appId: '1:955671967432:web:f7b91c86576cd40dadd7fd',
    messagingSenderId: '955671967432',
    projectId: 'campusconnect-firebase-project',
    authDomain: 'campusconnect-firebase-project.firebaseapp.com',
    storageBucket: 'campusconnect-firebase-project.firebasestorage.app',
    measurementId: 'G-L1ZZK8JES2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk3luNlgLun3JoUppcMjuW_McUK3F8ueQ',
    appId: '1:955671967432:android:24ff2272d9ef816aadd7fd',
    messagingSenderId: '955671967432',
    projectId: 'campusconnect-firebase-project',
    storageBucket: 'campusconnect-firebase-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNy55AwnkRsuJv2OTgcUjfWWqbtZtThB8',
    appId: '1:955671967432:ios:c3a3f6c262a2f02badd7fd',
    messagingSenderId: '955671967432',
    projectId: 'campusconnect-firebase-project',
    storageBucket: 'campusconnect-firebase-project.firebasestorage.app',
    iosBundleId: 'io.campusconnect.campusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNy55AwnkRsuJv2OTgcUjfWWqbtZtThB8',
    appId: '1:955671967432:ios:c3a3f6c262a2f02badd7fd',
    messagingSenderId: '955671967432',
    projectId: 'campusconnect-firebase-project',
    storageBucket: 'campusconnect-firebase-project.firebasestorage.app',
    iosBundleId: 'io.campusconnect.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY6pPYWVQAL4tONCV-W-i9l_5Jh3yRdjA',
    appId: '1:955671967432:web:1ba8b23c58201bcfadd7fd',
    messagingSenderId: '955671967432',
    projectId: 'campusconnect-firebase-project',
    authDomain: 'campusconnect-firebase-project.firebaseapp.com',
    storageBucket: 'campusconnect-firebase-project.firebasestorage.app',
    measurementId: 'G-52KHX2E7TD',
  );
}
